# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1124, 788)
        self.cargar = QtWidgets.QPushButton(Dialog)
        self.cargar.setGeometry(QtCore.QRect(40, 30, 93, 28))
        self.cargar.setObjectName("cargar")
        self.graficar = QtWidgets.QPushButton(Dialog)
        self.graficar.setGeometry(QtCore.QRect(130, 100, 93, 28))
        self.graficar.setObjectName("graficar")
        self.resultado = QtWidgets.QTextEdit(Dialog)
        self.resultado.setGeometry(QtCore.QRect(30, 460, 231, 181))
        self.resultado.setObjectName("resultado")
        self.MplWidget = QtWidgets.QWidget(Dialog)
        self.MplWidget.setGeometry(QtCore.QRect(330, 300, 691, 421))
        self.MplWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.MplWidget.setObjectName("MplWidget")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(440, 30, 571, 251))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.combox = QtWidgets.QComboBox(Dialog)
        self.combox.setGeometry(QtCore.QRect(170, 180, 161, 21))
        self.combox.setObjectName("combox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 180, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 230, 101, 16))
        self.label_2.setObjectName("label_2")
        self.comboy = QtWidgets.QComboBox(Dialog)
        self.comboy.setGeometry(QtCore.QRect(170, 230, 161, 21))
        self.comboy.setObjectName("comboy")
        self.combostack = QtWidgets.QComboBox(Dialog)
        self.combostack.setGeometry(QtCore.QRect(30, 410, 141, 21))
        self.combostack.setObjectName("combostack")
        self.estadistica = QtWidgets.QPushButton(Dialog)
        self.estadistica.setGeometry(QtCore.QRect(170, 410, 111, 28))
        self.estadistica.setObjectName("estadistica")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(180, 270, 68, 76))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_3 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.estado = QtWidgets.QTextEdit(Dialog)
        self.estado.setGeometry(QtCore.QRect(150, 30, 101, 31))
        self.estado.setObjectName("estado")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cargar.setText(_translate("Dialog", "LOAD DATA"))
        self.graficar.setText(_translate("Dialog", "GRAFICAR"))
        self.label.setText(_translate("Dialog", "Country:"))
        self.label_2.setText(_translate("Dialog", "State or Region:"))
        self.estadistica.setText(_translate("Dialog", "ESTADISTICAS"))
        self.radioButton.setText(_translate("Dialog", "Cases"))
        self.radioButton_3.setText(_translate("Dialog", "Deaths"))
        self.radioButton_2.setText(_translate("Dialog", "Both"))
